export const SIGN_UP_USER_SUCCESSFUL = 'SIGN_UP_USER_SUCCESSFUL'
export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE'
export const SIGN_UP_USER_LOADING = 'SIGN_UP_USER_LOADING'

export const SIGN_IN_USER_SUCCESSFUL = 'SIGN_IN_USER_SUCCESSFUL'
export const SIGN_IN_USER_FAILURE = 'SIGN_IN_USER_FAILURE'
export const SIGN_IN_USER_LOADING = 'SIGN_IN_USER_LOADING'

export const SIGN_OUT_USER_SUCCESSFUL = 'SIGN_OUT_USER_SUCCESSFUL'
