export const GET_USER_SUCCESSFUL = 'GET_USER_SUCCESSFUL'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'
export const GET_USER_LOADING = 'GET_USER_LOADING'

export const UPDATE_USER_SUCCESSFUL = 'UPDATE_USER_SUCCESSFUL'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'
export const UPDATE_USER_LOADING = 'UPDATE_USER_LOADING'